/* automatically generated by rust-bindgen 0.72.1 and then manually fixed */

use std::ffi::CStr;

pub type vr_PropertyContainerHandle_t = u64;
pub type vr_DriverHandle_t = vr_PropertyContainerHandle_t;

#[doc = " error codes returned by Vr_Init"]
#[repr(i32)]
pub enum VrInitError{
    None = 0,
    Unknown = 1,
    InitInstallationNotFound = 100,
    InitInstallationCorrupt = 101,
    InitVRClientDLLNotFound = 102,
    InitFileNotFound = 103,
    InitFactoryNotFound = 104,
    InitInterfaceNotFound = 105,
    InitInvalidInterface = 106,
    InitUserConfigDirectoryInvalid = 107,
    InitHmdNotFound = 108,
    InitNotInitialized = 109,
    InitPathRegistryNotFound = 110,
    InitNoConfigPath = 111,
    InitNoLogPath = 112,
    InitPathRegistryNotWritable = 113,
    InitAppInfoInitFailed = 114,
    InitRetry = 115,
    InitInitCanceledByUser = 116,
    InitAnotherAppLaunching = 117,
    InitSettingsInitFailed = 118,
    InitShuttingDown = 119,
    InitTooManyObjects = 120,
    InitNoServerForBackgroundApp = 121,
    InitNotSupportedWithCompositor = 122,
    InitNotAvailableToUtilityApps = 123,
    InitInternal = 124,
    InitHmdDriverIdIsNone = 125,
    InitHmdNotFoundPresenceFailed = 126,
    InitVRMonitorNotFound = 127,
    InitVRMonitorStartupFailed = 128,
    InitLowPowerWatchdogNotSupported = 129,
    InitInvalidApplicationType = 130,
    InitNotAvailableToWatchdogApps = 131,
    InitWatchdogDisabledInSettings = 132,
    InitVRDashboardNotFound = 133,
    InitVRDashboardStartupFailed = 134,
    InitVRHomeNotFound = 135,
    InitVRHomeStartupFailed = 136,
    InitRebootingBusy = 137,
    InitFirmwareUpdateBusy = 138,
    InitFirmwareRecoveryBusy = 139,
    InitUSBServiceBusy = 140,
    InitVRWebHelperStartupFailed = 141,
    InitTrackerManagerInitFailed = 142,
    InitAlreadyRunning = 143,
    InitFailedForVrMonitor = 144,
    InitPropertyManagerInitFailed = 145,
    InitWebServerFailed = 146,
    InitIllegalTypeTransition = 147,
    InitMismatchedRuntimes = 148,
    InitInvalidProcessId = 149,
    InitVRServiceStartupFailed = 150,
    InitPrismNeedsNewDrivers = 151,
    InitPrismStartupTimedOut = 152,
    InitCouldNotStartPrism = 153,
    InitPrismClientInitFailed = 154,
    InitPrismClientStartFailed = 155,
    InitPrismExitedUnexpectedly = 156,
    InitBadLuid = 157,
    InitNoServerForAppContainer = 158,
    InitDuplicateBootstrapper = 159,
    InitVRDashboardServicePending = 160,
    InitVRDashboardServiceTimeout = 161,
    InitVRDashboardServiceStopped = 162,
    InitVRDashboardAlreadyStarted = 163,
    InitVRDashboardCopyFailed = 164,
    InitVRDashboardTokenFailure = 165,
    InitVRDashboardEnvironmentFailure = 166,
    InitVRDashboardPathFailure = 167,
    DriverFailed = 200,
    DriverUnknown = 201,
    DriverHmdUnknown = 202,
    DriverNotLoaded = 203,
    DriverRuntimeOutOfDate = 204,
    DriverHmdInUse = 205,
    DriverNotCalibrated = 206,
    DriverCalibrationInvalid = 207,
    DriverHmdDisplayNotFound = 208,
    DriverTrackedDeviceInterfaceUnknown = 209,
    DriverHmdDriverIdOutOfBounds = 211,
    DriverHmdDisplayMirrored = 212,
    DriverHmdDisplayNotFoundLaptop = 213,
    DriverPeerDriverNotInstalled = 214,
    DriverWirelessHmdNotConnected = 215,
    IPCServerInitFailed = 300,
    IPCConnectFailed = 301,
    IPCSharedStateInitFailed = 302,
    IPCCompositorInitFailed = 303,
    IPCMutexInitFailed = 304,
    IPCFailed = 305,
    IPCCompositorConnectFailed = 306,
    IPCCompositorInvalidConnectResponse = 307,
    IPCConnectFailedAfterMultipleAttempts = 308,
    IPCConnectFailedAfterTargetExited = 309,
    IPCNamespaceUnavailable = 310,
    CompositorFailed = 400,
    CompositorD3D11HardwareRequired = 401,
    CompositorFirmwareRequiresUpdate = 402,
    CompositorOverlayInitFailed = 403,
    CompositorScreenshotsInitFailed = 404,
    CompositorUnableToCreateDevice = 405,
    CompositorSharedStateIsNull = 406,
    CompositorNotificationManagerIsNull = 407,
    CompositorResourceManagerClientIsNull = 408,
    CompositorMessageOverlaySharedStateInitFailure = 409,
    CompositorPropertiesInterfaceIsNull = 410,
    CompositorCreateFullscreenWindowFailed =
        411,
    CompositorSettingsInterfaceIsNull = 412,
    CompositorFailedToShowWindow = 413,
    CompositorDistortInterfaceIsNull = 414,
    CompositorDisplayFrequencyFailure = 415,
    CompositorRendererInitializationFailed =
        416,
    CompositorDXGIFactoryInterfaceIsNull = 417,
    CompositorDXGIFactoryCreateFailed = 418,
    CompositorDXGIFactoryQueryFailed = 419,
    CompositorInvalidAdapterDesktop = 420,
    CompositorInvalidHmdAttachment = 421,
    CompositorInvalidOutputDesktop = 422,
    CompositorInvalidDeviceProvided = 423,
    CompositorD3D11RendererInitializationFailed = 424,
    CompositorFailedToFindDisplayMode = 425,
    CompositorFailedToCreateSwapChain = 426,
    CompositorFailedToGetBackBuffer = 427,
    CompositorFailedToCreateRenderTarget = 428,
    CompositorFailedToCreateDXGI2SwapChain = 429,
    CompositorFailedtoGetDXGI2BackBuffer = 430,
    CompositorFailedToCreateDXGI2RenderTarget = 431,
    CompositorFailedToGetDXGIDeviceInterface =
        432,
    CompositorSelectDisplayMode = 433,
    CompositorFailedToCreateNvAPIRenderTargets =
        434,
    CompositorNvAPISetDisplayMode = 435,
    CompositorFailedToCreateDirectModeDisplay =
        436,
    CompositorInvalidHmdPropertyContainer = 437,
    CompositorUpdateDisplayFrequency = 438,
    CompositorCreateRasterizerState = 439,
    CompositorCreateWireframeRasterizerState =
        440,
    CompositorCreateSamplerState = 441,
    CompositorCreateClampToBorderSamplerState =
        442,
    CompositorCreateAnisoSamplerState = 443,
    CompositorCreateOverlaySamplerState = 444,
    CompositorCreatePanoramaSamplerState = 445,
    CompositorCreateFontSamplerState = 446,
    CompositorCreateNoBlendState = 447,
    CompositorCreateBlendState = 448,
    CompositorCreateAlphaBlendState = 449,
    CompositorCreateBlendStateMaskR = 450,
    CompositorCreateBlendStateMaskG = 451,
    CompositorCreateBlendStateMaskB = 452,
    CompositorCreateDepthStencilState = 453,
    CompositorCreateDepthStencilStateNoWrite =
        454,
    CompositorCreateDepthStencilStateNoDepth =
        455,
    CompositorCreateFlushTexture = 456,
    CompositorCreateDistortionSurfaces = 457,
    CompositorCreateConstantBuffer = 458,
    CompositorCreateHmdPoseConstantBuffer = 459,
    CompositorCreateHmdPoseStagingConstantBuffer
        = 460,
    CompositorCreateSharedFrameInfoConstantBuffer
        = 461,
    CompositorCreateOverlayConstantBuffer = 462,
    CompositorCreateSceneTextureIndexConstantBuffer
        = 463,
    CompositorCreateReadableSceneTextureIndexConstantBuffer
        = 464,
    CompositorCreateLayerGraphicsTextureIndexConstantBuffer
        = 465,
    CompositorCreateLayerComputeTextureIndexConstantBuffer
        = 466,
    CompositorCreateLayerComputeSceneTextureIndexConstantBuffer  = 467 ,
    CompositorCreateComputeHmdPoseConstantBuffer
        = 468,
    CompositorCreateGeomConstantBuffer = 469,
    CompositorCreatePanelMaskConstantBuffer =
        470,
    CompositorCreatePixelSimUBO = 471,
    CompositorCreateMSAARenderTextures = 472,
    CompositorCreateResolveRenderTextures = 473,
    CompositorCreateComputeResolveRenderTextures
        = 474,
    CompositorCreateDriverDirectModeResolveTextures
        = 475,
    CompositorOpenDriverDirectModeResolveTextures
        = 476,
    CompositorCreateFallbackSyncTexture = 477,
    CompositorShareFallbackSyncTexture = 478,
    CompositorCreateOverlayIndexBuffer = 479,
    CompositorCreateOverlayVertexBuffer = 480,
    CompositorCreateTextVertexBuffer = 481,
    CompositorCreateTextIndexBuffer = 482,
    CompositorCreateMirrorTextures = 483,
    CompositorCreateLastFrameRenderTexture =
        484,
    CompositorCreateMirrorOverlay = 485,
    CompositorFailedToCreateVirtualDisplayBackbuffer
        = 486,
    CompositorDisplayModeNotSupported = 487,
    CompositorCreateOverlayInvalidCall = 488,
    CompositorCreateOverlayAlreadyInitialized =
        489,
    CompositorFailedToCreateMailbox = 490,
    CompositorWindowInterfaceIsNull = 491,
    CompositorSystemLayerCreateInstance = 492,
    CompositorSystemLayerCreateSession = 493,
    CompositorCreateInverseDistortUVs = 494,
    CompositorCreateBackbufferDepth = 495,
    CompositorCannotDRMLeaseDisplay = 496,
    CompositorCannotConnectToDisplayServer =
        497,
    CompositorGnomeNoDRMLeasing = 498,
    CompositorFailedToInitializeEncoder = 499,
    CompositorCreateBlurTexture = 500,
    VendorSpecificUnableToConnectToOculusRuntime
        = 1000,
    VendorSpecificWindowsNotInDevMode = 1001,
    VendorSpecificOculusLinkNotEnabled = 1002,
    VendorSpecificHmdFoundCantOpenDevice =
        1101,
    VendorSpecificHmdFoundUnableToRequestConfigStart
        = 1102,
    VendorSpecificHmdFoundNoStoredConfig =
        1103,
    VendorSpecificHmdFoundConfigTooBig = 1104,
    VendorSpecificHmdFoundConfigTooSmall =
        1105,
    VendorSpecificHmdFoundUnableToInitZLib =
        1106,
    VendorSpecificHmdFoundCantReadFirmwareVersion
        = 1107,
    VendorSpecificHmdFoundUnableToSendUserDataStart
        = 1108,
    VendorSpecificHmdFoundUnableToGetUserDataStart
        = 1109,
    VendorSpecificHmdFoundUnableToGetUserDataNext
        = 1110,
    VendorSpecificHmdFoundUserDataAddressRange
        = 1111,
    VendorSpecificHmdFoundUserDataError = 1112,
    VendorSpecificHmdFoundConfigFailedSanityCheck
        = 1113,
    VendorSpecificOculusRuntimeBadInstall =
        1114,
    VendorSpecificHmdFoundUnexpectedConfiguration1
        = 1115,
    SteamSteamInstallationNotFound = 2000,
    LastError = 2001,
}

#[repr(C)]
pub struct vr_IVRDriverContext__bindgen_vtable {
    pub vr_IVRDriverContext_GetGenericInterface:
        unsafe extern "C" fn(
            this: *mut vr_IVRDriverContext,
            pchInterfaceVersion: *const ::std::os::raw::c_char,
            peError: *mut VrInitError,
        ) -> *mut ::std::os::raw::c_void,
    pub vr_IVRDriverContext_GetDriverHandle:
        unsafe extern "C" fn(this: *mut vr_IVRDriverContext) -> vr_DriverHandle_t,
}
#[doc = " This interface is provided by vrserver to allow the driver to notify\n the system when something changes about a device. These changes must\n not change the serial number or class of the device because those values\n are permanently associated with the device's index."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vr_IVRDriverContext {
    pub vtable_: *const vr_IVRDriverContext__bindgen_vtable,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vr_IVRDriverContext"][::std::mem::size_of::<vr_IVRDriverContext>() - 8usize];
    ["Alignment of vr_IVRDriverContext"][::std::mem::align_of::<vr_IVRDriverContext>() - 8usize];
};
#[repr(C)]
pub struct ServerTrackedDeviceProviderVtable {
    pub init: unsafe extern "C" fn(
        this: *mut ServerTrackedDeviceProvider,
        pDriverContext: *mut vr_IVRDriverContext,
    ) -> VrInitError,
    pub cleanup:
        unsafe extern "C" fn(this: *mut ServerTrackedDeviceProvider),
    pub get_interface_versions:
        unsafe extern "C" fn(
            this: *mut ServerTrackedDeviceProvider,
        ) -> *const *const ::std::os::raw::c_char,
    pub run_frame:
        unsafe extern "C" fn(this: *mut ServerTrackedDeviceProvider),
    pub should_block_standby_mode:
        unsafe extern "C" fn(this: *mut ServerTrackedDeviceProvider) -> bool,
    pub enter_standby:
        unsafe extern "C" fn(this: *mut ServerTrackedDeviceProvider),
    pub leave_standby:
        unsafe extern "C" fn(this: *mut ServerTrackedDeviceProvider),
}
#[doc = " This interface must be implemented in each driver. It will be loaded in vrserver.exe"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ServerTrackedDeviceProvider(*const ServerTrackedDeviceProviderVtable);

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vr_IServerTrackedDeviceProvider"]
        [::std::mem::size_of::<ServerTrackedDeviceProvider>() - 8usize];
    ["Alignment of vr_IServerTrackedDeviceProvider"]
        [::std::mem::align_of::<ServerTrackedDeviceProvider>() - 8usize];
};

pub const SERVER_TRACKED_DEVICE_PROVIDER_VERSION: &CStr = c"IServerTrackedDeviceProvider_004";

// I don't trust this.
unsafe extern "C" {
    #[link_name = "\u{1}_ZN2vrL19k_InterfaceVersionsE"]
    pub static k_InterfaceVersions: [*const ::std::os::raw::c_char; 13usize];
}