/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    #[link_name = "\u{1}_ZN2vrL19k_InterfaceVersionsE"]
    pub static vr_k_InterfaceVersions: [*const ::std::os::raw::c_char; 13usize];
}
